### ISSUE TITLE
[Task] Add Model information to the Openapi Spec

### ISSUE THREAD

**Issue by matgnt** [eclipse-esmf/esmf-sdk#340]
This is a feature request with low priority.

**Is your task related to a problem? Please describe.**
When I generate the code from the openapi spec, I want some basic model meta information included, e.g. the org name, model name, version, maybe more...

**Describe the solution you'd like**
Probably an enum with that kind of information, like 'XXModel.org' or 'XXModel.version' or 'XXModel.fullName'

**Describe alternatives you've considered**
I'm currently defining those additionally even though, the information would be available from the source of what is used to create the openapi spec.

Thanks for the tools,
Matthias Binzer

**Comment by matgnt** [comment]
Yes, probably a good idea to add the information to the metadata info object.
Since I'm not sure if all code generators would use this information and 'how', maybe to following could be an option, too.

Example TTL file:
https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.assembly_part_relationship/1.1.1/AssemblyPartRelationship.ttl#L33
(gen folder contains the generated files...)

A potential option could be something like:
```
components:
  schemas:
    ModelPrefixName:
      type: string
      enum:
      - "urn:bamm:io.catenax.assembly_part_relationship:1.1.1#"
    ModelName:
      type: string
      enum:
      - "AssemblyPartRelationship"
    ModelFullName:
      type: string
      enum:
      - "urn:bamm:io.catenax.assembly_part_relationship:1.1.1#AssemblyPartRelationship"

```
I think there is no other proper way to add some 'const' information to an openapi spec.

This would generate the enums that could be used. Disadvantage would be, when a version changes, also the enum names would change.
