### ISSUE TITLE
[Task] Improve openAPI Generator

### ISSUE THREAD

**Issue by DvSmi** [eclipse-esmf/esmf-sdk#733]
**Is your task related to a problem? Please describe.**
I want to create an OpenAPI description where you can reference the parameter definitions of other aspect models to the OpenAPI spec. Possible cases:

We want to create a get request for an aspect which has part of the aspect properties as parameter. The property is a String with a Regex to define what characters are allowed.
We then want to add the regex to the generated OpenAPI, but not by re-defining it in a parameter or a template file, but by referencing the property of an aspect model, e.g. the property containing in a namespace. So the template/parameter file does allow a reference in the schema which resolves the property and takes the regex from this property, which will be added to the generated OpenAPI specification in the end. 

**Describe the solution you'd like**
A possible way to solve this would be a dedicated property in a template/parameter file which defines the constraints of the property.
Example parameter file:
```
name:
  name: nameProperty
  in: query
  required: true
  referenceProperty: <com.example:1.0.0#nameProperty>
```
with a property defined in an aspect model:
```
<com.example:1.0.0#nameProperty> a samm:Property ;
    samm:preferredName "Name"@de ;
    samm:description "The property of a name."@en ;
    samm:exampleValue "Heinz" ;
    samm:characteristic :Name .

<com.example:1.0.0#Name> a samm-c:Trait ;
    samm-c:baseCharacteristic [
        a samm-c:Code ;
        samm:dataType xsd:string
    ] ;
    samm-c:constraint [
        a samm-c:RegularExpressionConstraint ;
        samm:value "[A-Z]{5,10}"
    ] .
```
which generates an OpenAPI specficiation for the request like:
```
    get:
      parameters:
      - name: nameProperty
        in: path
        description: The property of a name.
        required: true
        schema:
          type: string
          pattern: '[A-Z]'
          minLenth: 5
          maxLenth: 10
```
